CREATE TABLE IF NOT EXISTS `consoles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `slug` varchar(50) NOT NULL,
  `image` varchar(50) DEFAULT NULL,
  `pack_link` varchar(255) DEFAULT NULL,
  `bios_link` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unq_slug` (`slug`),
  KEY `slug` (`slug`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `consoles` (`id`, `name`, `slug`, `image`, `pack_link`, `bios_link`, `description`) VALUES
  (1, 'PlayStation', 'playstation', 'playstation.svg', NULL, 'http://example.com/', 'The PlayStation is a home video game console developed and marketed by Sony Computer Entertainment. The console was released on December 3, 1994 in Japan September 9, 1995 in North America, September 29, 1995 in Europe, and November 15, 1995 in Australia. The console was the first of the PlayStation lineup of home video game consoles. It primarily competed with the Nintendo 64 and the Sega Saturn. The PlayStation is the first "computer entertainment platform" to ship 100 million units, which it had reached 9 years and 6 months after its initial launch. In July 2000, a redesigned, slim version called the PS one was released, replacing the original grey console and named appropriately to avoid confusion with its successor, the PlayStation 2.  '),
  (2, 'PlayStation 2', 'playstation-2', 'playstation_2.svg', NULL, 'http://example.com/', 'The PlayStation 2 is a home video game console that was developed by Sony Computer Entertainment. It is the successor to the PlayStation and is the second installment in the PlayStation lineup of consoles. It was released in 2000 and competed with Sega\'s Dreamcast, Nintendo\'s GameCube and Microsoft\'s Xbox. It is the best-selling video game console of all time, selling over 155 million units, with 150 million confirmed by Sony in 2011. More than 3,874 game titles have been released for the PS2 since launch, and more than 1.5 billion copies have been sold. Sony later manufactured several smaller, lighter revisions of the console known as Slimline models in 2004. '),
  (3, 'GameCube', 'gamecube', 'gamecube.svg', '', NULL, 'The GameCube is a home video game console released by Nintendo in Japan and North America in 2001 and Europe and Australia in 2002. The sixth generation console is the successor to the Nintendo 64 and competed with Sony\'s PlayStation 2 and Microsoft\'s Xbox. The GameCube is the first Nintendo console to use optical discs as its primary storage medium. The discs are in the miniDVD format; as a result of their smaller size and the console\'s small disc compartment.The console supports online gaming for a small number of games via the broadband or modem adapter and connects to the Game Boy Advance via the link cable, allowing players to access exclusive in-game features. Reception of the GameCube was generally positive. The console was praised for its controller, extensive software library and high-quality games, but was criticized for its exterior design and lack of features. '),
  (4, 'Nintendo 64', 'nintendo-64', 'nintendo_64.svg', 'http://example.com/', NULL, 'The Nintendo 64 is Nintendo\'s third home video game console for the international market. Named for its 64-bit central processing unit, it was released in June 1996 in Japan, September 1996 in North America and Brazil, March 1997 in Europe and Australia, September 1997 in France. It was the last major home console to use the cartridge as its primary storage format (until Nintendo\'s seventh console, the Nintendo Switch in 2017). Despite being succeeded by the GameCube, the Nintendo 64 remained on store shelves until mid 2002 when it was discontinued. As part of the fifth generation of gaming, the system competed primarily with the Sony PlayStation and the Sega Saturn. The Nintendo 64 remains one of the most recognized video game systems in history.'),
  (5, 'Dreamcast', 'dreamcast', 'dreamcast.svg', NULL, 'http://example.com/', 'The Sega Dreamcast is Sega\'s fifth and final Console and the successor to the Sega Saturn. Hoping to recapture the Video Game Market, it was designed to supersede both the Playstation and the Nintendo 64. Originally released sixteen months before the PlayStation 2, and three years before the Nintendo GameCube and the Microsoft Xbox, it was considered to be ahead of its time and was initially successful at restoring Sega\'s reputation in the gaming industry. However, it failed to gain enough momentum before the release of Sony\'s PlayStation 2 in March 2000, and Sega decided to discontinue the Sega Dreamcast the next year, withdrawing entirely from the Console Hardware business.'),
  (6, 'Atari 2600', 'atari-2600', 'atari_2600.svg', 'http://example.com/', NULL, 'The Atari Video Computer System is a cartridge-based game console released in 1977. Atari\'s prior success with Pong, both in arcades and in the home, lead to the development of the VCS.\r\nIt was largely successful due home versions of arcade games such as Asteroids, Space Invaders, and Centipede as well as first and third party games developed specifically for the console, such as Pitfall and Adventure. The Atari 2600 made the home video game market mainstream, selling 30 million units worldwide before being discontinued in January 1, 1992.'),
  (7, 'Commodore 64', 'commodore-64', 'commodore_64_2.svg', 'http://example.com/', 'The Commodore 64, also known as the C64 or the CBM 64, is an 8-bit home computer introduced in January 1982 by Commodore International. It has been listed in the Guinness World Records as the highest-selling single computer model of all time, with independent estimates placing the number sold between 10 and 17 million units. With support for multicolor sprites and a custom chip for waveform generation, the C64 could create superior visuals and audio compared to systems without such custom hardware. '),
  (8, 'Game Gear', 'game-gear', 'sega_game_gear.svg', 'http://example.com/', NULL, 'The Game Gear is an 8-bit fourth generation hand-held game console released by Sega on October 6, 1990 in Japan, in April 1991 throughout North America and Europe and during 1992 in Australia. The Game Gear primarily competed with Nintendo\'s Game Boy, the Atari Lynx, and NEC\'s TurboExpress. The hand-held shares much of its hardware with the Master System and is able to play its own titles as well as those of the Master System, the latter being made possible by the use of an adapter. Containing a full-color back-lit screen with a landscape format, Sega positioned the Game Gear as a technologically superior hand-held to the Game Boy.'),
  (9, 'Game Boy', 'gameboy', 'gameboy.svg', 'http://example.com/', NULL, 'The Game Boy is an 8-bit handheld game console which was developed and manufactured by Nintendo and first released on April 21, 1989 in North America on July 31, 1989 and in Europe on September 28, 1990. The Game Boy is Nintendo\'s first handheld game console and it combined features from both the Nintendo Entertainment System and Game & Watch. During its early lifetime, the Game Boy mainly competed with Sega\'s Game Gear, Atari\'s Lynx, and NEC\'s TurboExpress. The Game Boy outsold its rivals and became a significant success. Upon the Game Boy\'s release in the United States, its entire shipment of one million units was sold within a few weeks.'),
  (10, 'Game Boy Color', 'gameboy-color', 'gameboy_color.svg', 'http://example.com/', NULL, 'The Game Boy Color (GBC) is a hand-held game console manufactured by Nintendo, which was released on October 21, 1998 in Japan and was released in November of the same year in international markets. It is the successor of the Game Boy. The Game Boy Color features a color screen. It is slightly thicker and taller and features a slightly smaller screen than the Game Boy Pocket, its predecessor. The spelling of the system\'s name remains consistent throughout the world with its American English spelling of color. '),
  (11, 'Sega Genesis', 'sega-genesis', 'sega_genesis.svg', 'http://example.com/', NULL, 'The Sega Genesis, known as the Mega Drive in regions outside of North America, is a 16-bit home video game console developed and sold by Sega. The system plays a library of more than 900 games created by Sega and a wide array of third-party publishers and delivered on ROM-based cartridges. In Japan, the Mega Drive did not fare well against its two main competitors, the Super Nintendo Entertainment System and NEC\'s PC Engine, but it achieved considerable success in North America, Brazil, and Europe.'),
  (12, 'Super NES', 'snes', 'snes.svg', 'http://example.com/', NULL, 'The Super Nintendo Entertainment System is a 16-bit home video game console developed by Nintendo that was released in 1990 in Japan and South Korea, 1991 in North America, 1992 in Europe and Australasia (Oceania), and 1993 in South America. In Japan, the system is called the Super Famicom. In South Korea, it is known as the Super Comboy. The system was released in Brazil on August 30, 1993. Although each version is essentially the same, several forms of regional lockout prevent the different versions from being compatible with one another. The console introduced advanced graphics and sound capabilities compared with other systems at the time. The development of a variety of enhancement chips integrated in game cartridges helped to keep it competitive in the marketplace. The SNES was a global success, becoming the best-selling console of the 16-bit era despite its relatively late start and the intense competition it faced in North America and Europe from Sega\'s Genesis console. The SNES remained popular well into the 32-bit era having sold 49.1 million worldwide. It continues to be popular among collectors and retro gamers, some of whom still make home-brew ROM images, in addition to its popularity in Nintendo\'s emulated re-releases, such as in WiiWare environment.'),
  (13, 'PlayStation Portable', 'playstation-portable', 'psp.svg', NULL, NULL, 'The PlayStation Portable (PSP) is a handheld game console developed by Sony Computer Entertainment. Development of the handheld was announced during E3 2003, and it was unveiled on May 11, 2004, at a Sony press conference before E3 2004. The system was released in Japan on December 12, 2004, in North America on March 24, 2005, and in the PAL region on September 1, 2005. It primarily competed with the Nintendo DS, as part of the seventh generation of video games consoles. '),
  (14, 'Sega Saturn', 'sega-saturn', 'sega_saturn.svg', NULL, 'http://example.com/', 'The Sega Saturn is a 32-bit fifth-generation home video game console developed by Sega and released on November 22, 1994 in Japan, May 11, 1995 in North America, and July 8, 1995 in Europe. The successor to the successful Sega Genesis, the Saturn has a dual-CPU architecture and eight processors. Its games are in CD-ROM format, and the game library contains several arcade ports as well as original games. Development of the Saturn began in 1992, the same year Sega\'s groundbreaking 3D Model 1 arcade hardware debuted. Designed around a new CPU from Japanese electronics company Hitachi, another video display processor was incorporated into the system\'s design in early 1994 to better compete with Sony\'s forthcoming PlayStation. The Saturn was initially successful in Japan, but failed to sell in large numbers in the United States after its surprise May 1995 launch, four months before its scheduled release date. After the debut of the Nintendo 64 in late 1996, the Saturn rapidly lost market share in the U.S., where it was discontinued in 1998. Having sold 9.26 million units worldwide, the Saturn is considered a commercial failure.'),
  (15, 'Nintendo DS', 'nintendo-ds', 'nintendo_ds.svg', NULL, 'http://example.com/', 'The Nintendo DS is a dual-screen hand-held game console developed and released by Nintendo. The device went on sale in North America on November 21, 2004. The DS, short for "Developers\' System" or "Dual Screen", introduced distinctive new features to hand-held gaming: two LCD screens working in tandem (the bottom one featuring a touchscreen), a built-in microphone, and support for wireless connectivity. The Nintendo DS also features the ability for multiple DS consoles to directly interact with each other over Wi-Fi within a short range without the need to connect to an existing wireless network. Alternatively, they could interact on-line using the now-defunct Nintendo Wi-Fi Connection service. Its main competitor was Sony\'s PlayStation Portable as part of the seventh generation era. '),
  (16, 'Nintendo DS\r\n (Download Play)', 'nintendo-ds-download-play', 'nintendo_ds.svg', NULL, NULL, 'The Nintendo DS is a dual-screen hand-held game console developed and released by Nintendo. The device went on sale in North America on November 21, 2004. The DS, short for "Developers\' System" or "Dual Screen", introduced distinctive new features to hand-held gaming: two LCD screens working in tandem (the bottom one featuring a touchscreen), a built-in microphone, and support for wireless connectivity. The Nintendo DS also features the ability for multiple DS consoles to directly interact with each other over Wi-Fi within a short range without the need to connect to an existing wireless network. Alternatively, they could interact on-line using the now-defunct Nintendo Wi-Fi Connection service. Its main competitor was Sony\'s PlayStation Portable as part of the seventh generation era. '),
  (17, 'Nintendo DSi', 'nintendo-dsi-dlc', 'nintendo_dsi.svg', NULL, NULL, 'The Nintendo DS is a dual-screen hand-held game console developed and released by Nintendo. The device went on sale in North America on November 21, 2004. The DS, short for "Developers\' System" or "Dual Screen", introduced distinctive new features to hand-held gaming: two LCD screens working in tandem (the bottom one featuring a touchscreen), a built-in microphone, and support for wireless connectivity. The Nintendo DS also features the ability for multiple DS consoles to directly interact with each other over Wi-Fi within a short range without the need to connect to an existing wireless network. Alternatively, they could interact on-line using the now-defunct Nintendo Wi-Fi Connection service. Its main competitor was Sony\'s PlayStation Portable as part of the seventh generation era. '),
  (18, 'Atari 5200', 'atari-5200', 'atari_5200.svg', 'http://example.com/', 'The Atari 5200 SuperSystem, commonly known as the Atari 5200, is a video game console that was introduced in 1982 by Atari Inc. as a higher end complementary console for the popular Atari 2600.\r\nThe 5200 was created to compete with the Intellivision, but wound up more directly competing with the ColecoVision shortly after its release.'),
  (19, 'Atari 7800', 'atari-7800', 'atari_7800.svg', 'http://example.com/', 'The Atari 7800 ProSystem is a game console made by Atari. It was developed after the failure of the Atari 5200, with the intent on releasing the system in 1984, but due to the Great Video Game Crash, as well as numerous changes at Atari, the system was shelved for a couple of years. By the time Atari did release it, the Nintendo Entertainment System and Sega Master System had already surpassed the 7800\'s capabilities, and the runaway success of the NES helped doom Atari to also-ran status through the third generation of video game consoles. '),
  (20, 'Jaguar', 'jaguar', 'jaguar.svg', 'http://example.com/', NULL, 'The Atari Jaguar is a home video game console that was developed by Atari Corporation. The console is the sixth programmable console to be developed under the Atari brand, originally released in North America in November 1993. It is also the last Atari console to use physical media. The multi-chip architecture, hardware bugs, and lacking developer support tools made game development difficult. Underwhelming sales further contributed to the console\'s lack of third-party support. This, in addition to the lack of internal development at Atari, led to a games library comprising only 56 licensed titles. Atari attempted to extend the lifespan of the system with the Atari Jaguar CD add-on and marketing the Jaguar as the low-cost next generation console. With the release of the Sega Saturn and Sony PlayStation in 1995, sales of the Jaguar continued to fall, ultimately selling no more than 250,000 units before it was discontinued in 1996.'),
  (21, 'Lynx', 'lynx', 'lynx.svg', 'http://example.com/', 'The Atari Lynx is a 16-bit hand-held game console that was released by Atari Corporation in September 1989 in North America, and in Europe and Japan in 1990. It was the world\'s first hand-held electronic game with a color LCD. It was also notable for its advanced graphics and ambidextrous layout. The Lynx competed with the Game Boy (released two months earlier), as well as the Game Gear and TurboExpress, both released the following year. It was discontinued in 1996. '),
  (22, 'Atari ST', 'atari-st', 'atari_st.svg', 'http://example.com/', 'The Atari ST was a microcomputer developed by Atari Corporation in the mid 1980s. It was announced in January of 1985, and released in June of that year. It runs on the Motorola 68000 CPU. "ST" stands for sixteen/thirty-two, in reference to the 16-bit external bus and 32-bit internals of the 68000 chip. It ran Digital Research\'s GEM (Graphical Environment Manager) on Atari\'s proprietary TOS (The Operating System). It primarily competed with the Macintosh and the Amiga in most markets. '),
  (23, 'WonderSwan', 'wonderswan', 'wonderswan.svg', 'http://example.com/', NULL, 'The WonderSwan is a hand-held game console released in Japan by Bandai. Released in 1999 in the fifth generation of video game consoles, the WonderSwan and its two later models, the WonderSwan Color and SwanCrystal were officially supported until being discontinued by Bandai in 2003. During its lifespan, no variation of the WonderSwan was released outside of Japan. Powered by a 16-bit central processing unit, the WonderSwan took advantage of a low price point and long battery life in comparison to its competition, Nintendo\'s Game Boy Color and SNK\'s Neo Geo Pocket Color. Later improvements took advantage of quality upgrades to the hand-held\'s screen and added color. The WonderSwan is playable both vertically and horizontally, and features a unique library of games, including numerous first-party titles based on licensed anime properties, as well as significant third-party support from Square, Namco, and Taito. Overall, the WonderSwan in all its variations combined to sell an estimated 3.5 million units and managed to obtain as much as 8% of the Japanese hand-held video game console market before being marginalized by Nintendo\'s Game Boy Advance. Retrospective feedback praises the potential of the WonderSwan despite its low sales and its brief time holding its own against Nintendo in the marketplace.'),
  (24, 'WonderSwan Color', 'wonderswan-color', 'wonderswan_color.svg', 'http://example.com/', NULL, 'The WonderSwan Color was released on December 30, 2000 and only in Japan. It was created by Bandai, and the successor to the original WonderSwan. It was met with modest success and sales (especially considering Nintendo\'s near-monopoly of the hand-held market). The market share of the WonderSwan Color was approximately 8%, according to Bandai. Much of this success is credited to the low price of the hand-held; ¥6800, or $59. The WonderSwan Color also had great third party support, with companies such as Squaresoft (who ported many of the original Final Fantasy games to the WonderSwan Color). When the WonderSwan Color\'s successor, the SwanCrystal, was released, Nintendo had regained support of Squaresoft, however. One of the unique features of the WonderSwan (all versions) was the fact that it could be played either horizontally or vertically.'),
  (25, 'Casio Loopy', 'loopy', 'loopy.svg', 'http://example.com/', 'The Casio Loopy is a 32-bit home video game console. Released exclusively in Japan in October 1995, it was unique in that the marketing for it was completely targeted to female gamers. '),
  (26, 'Amiga', 'amiga', 'amiga.svg', 'http://example.com/', 'The Amiga is a family of personal computers introduced by Commodore in 1985. The original model was part of a wave of 16 and 32 bit computers that featured 256 KB or more of RAM, mouse-based GUIs, and significantly improved graphics and audio over 8-bit systems. This wave included the Atari STâ€”released the same yearâ€”Apple\'s Macintosh, and later the Apple IIGS. Based on the Motorola 68000 microprocessor, the Amiga differed from its contemporaries through the inclusion of custom hardware to accelerate graphics and sound, including sprites and a blitter, and a pre-emptive multitasking operating system called AmigaOS.'),
  (27, 'Virtual Boy', 'virtual-boy', 'virtual_boy.svg', 'http://example.com/', NULL, 'The Virtual Boy is a 32-bit table-top video game console developed and manufactured by Nintendo. Released in 1995, it was marketed as the first console capable of displaying stereoscopic 3D graphics. The player uses the console in a manner similar to a head-mounted display, placing their head against the eyepiece to see a red monochrome display. The games use a parallax effect to create the illusion of depth. Sales failed to meet targets, and by early 1996, Nintendo ceased distribution and game development, only ever releasing 22 games for the system. '),
  (28, 'N-Gage', 'n-gage', 'n_gage.svg', 'http://example.com/', NULL, 'The N-Gage is a PDA combining features of a telephone and a hand-held game system developed by Nokia, announced on November, 4 2002 and released on October, 7 2003. N-Gage attempted to lure gamers away from the Game Boy Advance by including telephone functionality. This was unsuccessful, partly because the buttons, designed for a telephone, were not well-suited for gaming, and the original N-Gage was described as resembling a taco, which led to its mocking nickname "Taco phone".'),
  (29, 'NES', 'nes', 'nes.svg', 'http://example.com/', NULL, 'The Nintendo Entertainment System (commonly abbreviated as NES) is an 8-bit home video game console that was developed and manufactured by Nintendo. It was initially released in Japan as the Family Computer more commonly known by the portmanteau abbreviation Famicom. The best-selling gaming console of its time, the NES helped revitalize the US video game industry following the North American video game crash of 1983. With the NES, Nintendo introduced a now-standard business model of licensing third-party developers, authorizing them to produce and distribute titles for Nintendo\'s platform.'),
  (30, 'Game Boy Advance', 'gameboy-advance', 'gba.svg', 'http://example.com/', NULL, 'The Game Boy Advance (GBA) is a 32-bit hand-held video game console developed, manufactured and marketed by Nintendo as the successor to the Game Boy Color. It was released in Japan on March 21, 2001 in North America on June 11, 2001 in Australia and Europe on June 22, 2001 and in mainland China on June 8, 2004. Nintendo\'s competitors in the hand-held market at the time were the Neo Geo Pocket Color, WonderSwan, GP32, Tapwave Zodiac, and the N-Gage. Despite the competitors\' best efforts, Nintendo maintained a majority market share with the Game Boy Advance. '),
  (31, 'Sega Master System', 'sega-master-system', 'master_system.svg', 'http://example.com/', 'The Master System is a third-generation home video game console manufactured by Sega between 1985 and 1992. It was originally released in 1985 as the Sega Mark III in Japan, and was renamed and redesigned for overseas markets, launching in 1986 in North America, 1987 in Europe, and 1989 in Brazil. It was re-released in Japan in 1987 with additional features. The Master System featured accessories such as a light gun and 3D glasses designed to work with a range of specially coded games. It was released in competition with the Nintendo Entertainment System, had fewer well-reviewed games than the NES and a smaller library due to Nintendo licensing policies requiring platform exclusivity. Despite the Master System\'s newer hardware, it it failed to overturn Nintendo\'s significant market share advantage in Japan and North America. However, it attained significantly more success in Europe and Brazil. '),
  (32, 'Sega 32X', 'sega-32x', '32x.svg', 'http://example.com/', NULL, 'The 32X is an add-on for the Sega Genesis video game console. It was designed to expand the power of the Genesis and serve as a transitional console into the 32-bit era until the release of the Sega Saturn. Independent of the Genesis, the 32X uses its own ROM cartridges and has its own library of games. The 32X was presented as a low-cost option for consumers looking to play 32-bit games. Developed in response to the Atari Jaguar and concerns that the Saturn would not make it to market by the end of 1994, the product was conceived as an entirely new console. The 32X is considered a commercial failure. Reception after the add-on\'s unveiling and launch was positive, highlighting the low price of the system and power expansion to the Genesis. Later reviews, both contemporary and retrospective, for the 32X have been mostly negative because of its shallow game library, poor market timing and the resulting market fragmentation for the Genesis. '),
  (33, 'Sega PICO', 'sega-pico', 'pico.svg', 'http://example.com/', NULL, 'The Sega Pico, also known as Kids Computer Pico, is an educational video game console by Sega Toys. Marketed as "edutainment", the main focus of the Pico was educational video games for children between 3 and 7 years old. The Pico was released in June 1993 in Japan and November 1994 in North America and Europe, later reaching China. It was succeeded by the Advanced Pico Beena, which was released in Japan in 2005. Though the Pico was sold continuously in Japan through the release of the Beena, in North America and Europe the Pico was less successful and was discontinued in early 1998, later being rereleased by Majesco Entertainment. Releases for the Pico were focused on education for children and included titles supported by licensed franchised animated characters, including Sega\'s own Sonic the Hedgehog series. Overall, Sega claims sales of 3.4 million Pico consoles and 11.2 million game cartridges, and over 350,000 Beena consoles and 800,000 cartridges.'),
  (34, 'Sega SG-1000', 'sega-sg-1000', 'sg_1000.svg', 'http://example.com/', NULL, 'The SG-1000 also known as the Sega Computer Video Game SG-1000, is a home video game console manufactured by Sega and released in Japan, Australia, and other regions. It was Sega\'s first entry into the home video game hardware business, and provided the basis for the more successful Master System. Introduced in 1983, the SG-1000 was released on the same day that Nintendo released the Nintendo Entertainment System. Due to the release of the NES, and the number of consoles present in the market at the time, the SG-1000 was not commercially successful. '),
  (35, 'Nintendo Famicom', 'famicom', 'famicom.svg', 'http://example.com/', 'The Nintendo Entertainment System (commonly abbreviated as NES) is an 8-bit home video game console that was developed and manufactured by Nintendo. It was initially released in Japan as the Family Computer more commonly known by the portmanteau abbreviation Famicom. The best-selling gaming console of its time, the NES helped revitalize the US video game industry following the North American video game crash of 1983. With the NES, Nintendo introduced a now-standard business model of licensing third-party developers, authorizing them to produce and distribute titles for Nintendo\'s platform.'),
  (36, 'Nintendo Satellaview', 'satellaview', 'satellaview.svg', 'http://example.com/', 'The Satellaview was a retail satellite modem that was made specifically for the Super Famicom. It was never released in America or Europe. The Satellaview, a Nintendo developed and sold device, used the St. GIGA satellite radio service, through which game data was broadcast during a special segment called Super Famicom Hour. During the broadcast time people could download games to the Satellaview\'s internal memory or an optional Memory Pak. Unlike competing services, the Satellaview did not have online multiplayer due to the one-way nature of satellite radio. However, limited amounts of data could be sent back through the radio connection; quizzes and other competitions which allowed players to submit answers were common. Until 1999 the Satellaview service was controlled by both St. GIGA and Nintendo. After 1999 St. GIGA was the sole controller of the service, as Nintendo broke its partnership with the radio station due to a dispute. However, the service was only turned off in 2000. '),
  (37, 'Casio PV-1000', 'pv-1000', 'casio_pv1000.svg', 'http://example.com/', NULL, 'The Casio PV-1000 launched in Japan in October 1983. The console was based on technology from the previous generation, such as the ColecoVision. Faced with competition from the likes of the Sega SG-1000 and the Nintendo Famicom, the PV-1000 did not last long, in some places disappearing within a matter of weeks. Though the PV-1000 console failed, Casio remodeled the console into a computer known as the PV-2000 which is compatible with PV-1000 controllers but not games and released it in December 1983.'),
  (38, 'ColecoVision', 'colecovision', 'colecovision.svg', 'http://example.com/', 'The ColecoVision is Coleco Industries\' second-generation home video-game console that was released in August 1982. The ColecoVision offered a closer experience to more powerful arcade game systems compared to competitors such as the Atari 2600, along with the means to expand the system\'s basic hardware. '),
  (39, 'Arcadia 2001', 'arcadia-2001', 'arcadia_2001.svg', 'http://example.com/', NULL, 'Arcadia 2001 is a second-generation 8-bit console released by Emerson Radio in 1982 following the release of ColecoVision.\r\nIt was discontinued only 18 months later, with a total of 35 games having been released.'),
  (40, 'Adventure Vision', 'adventure-vision', 'adventure_vision.svg', 'http://example.com/', 'The Entex Adventure Vision is a cartridge based game made in 1982. It created a display by using a single vertical column of 40 LEDs, and a spinning mirror to simulate 150 vertical rows (thus basically making it 150x40 resolution).\r\nOnly four games were ever made for it, all based on arcade games: Defender, Turtles, Super Cobra and Space Force.'),
  (41, 'Fairchild Channel F', 'channel-f', 'channel_f.svg', 'http://example.com/', 'The Fairchild Channel F is a home video game console released by Fairchild Semiconductor in November 1976 across North America. It was also released in Japan in October the following year. It has the distinction of being the first programmable ROM cartridge–based video game console, and the first console to use a microprocessor. It was launched as the Video Entertainment System, or VES, but when Atari released its VCS the next year, Fairchild renamed its machine.'),
  (42, 'Funtech Super A\'Can', 'super-acan', 'super_acan.svg', 'http://example.com/', NULL, 'The Super A\'can is a home video game console that was released exclusively in Taiwan in 1995 by Funtech/Dunhuang Technology. Inside is a Motorola 68000, also used in the Sega Genesis and Neo Geo. Twelve games have been confirmed to exist for the system. '),
  (43, 'GamePark GP32', 'gp32', 'gp32.svg', 'http://example.com/', 'The GP32 (GamePark 32) is a hand-held game console developed by the Korean company Game Park. It was released on November 23, 2001, in South Korea only. The overall design is not unlike the original version of the Game Boy Advance. Unlike other hand held gaming systems, which tend to be proprietary cartridge-based, the GP32 uses SmartMedia cards (SMC) for storing programs and data, making it accessible for amateur developers as no further development hardware is required. '),
  (44, 'Vectrex', 'vectrex', 'vectrex.svg', 'http://example.com/', NULL, 'The Vectrex is a vector display-based home video game console that was developed by Western Technologies/Smith Engineering. It was licensed and distributed first by General Consumer Electronics (GCE), and then by Milton Bradley Company after its purchase of GCE. It was released in November 1982. The Vectrex exited the console market in early 1984. Unlike other non-portable video game consoles, which connected to televisions and rendered raster graphics, the Vectrex has an integrated vector monitor which displays vector graphics. The Vectrex is monochrome and uses plastic screen overlays to simulate color and various static graphics and decorations. At the time, many of the most popular arcade games used vector displays, and through a licensing deal with Cinematronics, GCE was able to produce high-quality versions of arcade games such as Space Wars and Armor Attack. Vectrex comes with a built-in game, Mine Storm. A light pen was also available, and in 1984 it became the first home system to offer a 3D peripheral (the Vectrex 3D Imager), predating the Master System\'s SegaScope 3D by several years. Despite being a commercial failure, the console received positive reviews and had gained a devote cult following. '),
  (45, 'Magnavox Odyssey²', 'odyssey-2', 'odyssey_2.svg', 'http://example.com/', 'The Magnavox Odyssey², also known as Philips Odyssey² is a second generation home video game console released in 1978. It was sold in Europe as the Philips Videopac G7000, in Brazil as the Philips Odyssey and in Japan as Odyssey2. Odyssey² was one of the major three home consoles prior to the 1983 video game market crash, along with Atari 2600 and IntelliVision. '),
  (46, 'Intellivision', 'intellivision', 'intellivision.svg', 'http://example.com/', 'The Intellivision is a home video game console released by Mattel Electronics in 1979. Development of the console began in 1977, the same year as the introduction of its main competitor, the Atari 2600. Game development started in 1978 and continued until 1990 when the Intellivision was discontinued. From 1980 to 1983 over 3 million Intellivision units were sold. In 2009, video game website IGN named the Intellivision the No. 14 greatest video game console of all time.'),
  (47, 'MSX', 'msx', 'msx.svg', 'http://example.com/', 'MSX is a standardized home computer architecture, first announced by Microsoft on June 16, 1983. Microsoft conceived the project as an attempt to create unified standards among various hardware makers of the period; which ultimately failed. They were popular in Japan and several other countries. It is difficult to estimate how many MSX computers were sold worldwide, but eventually 5 million MSX-based units were sold in Japan alone. Despite Microsoft\'s involvement, the MSX-based machines were seldom released in the United States. Before the great success of Nintendo\'s Family Computer, MSX was the platform for which major Japanese game studios, such as Konami and Hudson Soft, produced video games. The Metal Gear series, for example, was originally written for MSX hardware.'),
  (48, 'MSX2', 'msx2', 'msx2.svg', 'http://example.com/', 'MSX is a standardized home computer architecture, first announced by Microsoft on June 16, 1983. Microsoft conceived the project as an attempt to create unified standards among various hardware makers of the period; which ultimately failed. They were popular in Japan and several other countries. It is difficult to estimate how many MSX computers were sold worldwide, but eventually 5 million MSX-based units were sold in Japan alone. Despite Microsoft\'s involvement, the MSX-based machines were seldom released in the United States. Before the great success of Nintendo\'s Family Computer, MSX was the platform for which major Japanese game studios, such as Konami and Hudson Soft, produced video games. The Metal Gear series, for example, was originally written for MSX hardware.'),
  (49, 'TurboGrafx-16', 'turbografx-16', 'turbografx_16.svg', 'http://example.com/', NULL, 'The TurboGrafx-16 Entertainment SuperSystem, known in Japan and France as the PC Engine, is a home video game console manufactured and marketed by NEC Home Electronics, and designed by Hudson Soft. It was released in Japan on October 30, 1987 and in the United States on August 29, 1989. It also had a limited release in the United Kingdom and Spain in 1990, known as simply TurboGrafx and based on the American model, while the Japanese model was imported and distributed in France in 1989. It was the first console released in the 16-bit era, although it used an 8-bit CPU. Originally intended to compete with the Nintendo Entertainment System (NES), it ended up competing with the Sega Genesis, and later on the Super Nintendo Entertainment System (SNES). The TurboGrafx-16 failed to break into the North American market and sold poorly, which has been blamed on inferior marketing. However, in Japan, the PC Engine, introduced into the market at a much earlier date, was very successful, where it gained strong third-party support and outsold the Famicom at its 1987 debut, eventually becoming the Super Famicom\'s main rival.'),
  (50, 'SuperGrafx', 'supergrafx', 'supergrafx.svg', 'http://example.com/', NULL, 'The PC Engine SuperGrafx, also shortened as the SuperGrafx or PC Engine SG, is a video game console by NEC Home Electronics, released exclusively in Japan. It is an upgraded version of the PC Engine, released two years prior. The machine was purported to be a true 16-bit system with improved graphics and audio capabilities over the original PC Engine. Expected to be released in 1990, the SuperGrafx was rushed to market, debuting several months earlier in late 1989 with only modest improvements over the original PC Engine. Only six retail games were produced which took advantage of the improved SuperGrafx hardware. The SuperGrafx is backwards compatible with all PC Engine software in both HuCard and CD-ROM² format, bringing the compatible software total up to nearly 700. Due to its commercial failure, none of the added hardware enhancements were carried over to the later PC Engine Duo consoles. '),
  (51, 'Videopac+', 'videopac-plus', 'videopac_plus.svg', 'http://example.com/', NULL, 'The Philips Videopac+ G7400 is a video game console released in limited quantities in 1983 and only in Europe; an American release as the Odyssey³ Command Center was planned but never occurred. The G7400 was the successor to the Philips Videopac G7000, the European counterpart to the American Magnavox Odyssey². The system featured excellently tailored background and foreground graphics.'),
  (52, 'RCA Studio II', 'rca-studio-ii', 'rca_studio_ii.svg', 'http://example.com/', 'The RCA Studio II is a home video game console made by RCA that debuted in January 1977. The graphics of Studio II games were black and white and resembled those of earlier Pong consoles and their clones. The Studio II also did not have joysticks or similar game controllers but instead used two ten-button keypads that were built into the console itself. The console was capable of making simple beep sounds with slight variations in tone and length. The Studio II included five built-in games. The Studio II was not a successful product; the previously released Fairchild Channel F made it obsolete at launch and it suffered a final decisive blow when the superior Atari 2600 console was released only 10 months later. After poor Christmas sales in 1977, RCA ceased production of the Studio II and offloaded excess inventory to Radio Shack in a fire sale. '),
  (53, 'Neo Geo Pocket Color', 'neo-geo-pocket-color', 'neo_geo_pocket_color.svg', 'http://example.com/', 'The Neo Geo Pocket Color is a 16-bit color hand-held video game console manufactured by SNK. It is a successor to SNK\'s monochrome Neo Geo Pocket hand-held which debuted in 1998 in Japan, with the Color being fully backward compatible. The Neo Geo Pocket Color was released on March 16, 1999 in Japan, August 6, 1999 in North America, and on October 1, 1999 in Europe. Despite its failure the Neo Geo Pocket Color has been regarded as an influential system. Many highly acclaimed games were released for the system, such as SNK vs. Capcom: The Match of the Millennium, King of Fighters R-2, and other quality arcade titles derived from SNK\'s MVS and AES. It also featured an arcade-style micro-switched \'clicky stick\' joystick, which was praised for its accuracy and being well-suited for fighting games. The system\'s display and 40-hour battery life were also well received.'),
  (54, 'Neo Geo Pocket', 'neo-geo-pocket', 'neo_geo_pocket.svg', 'http://example.com/', 'The Neo Geo Pocket is a monochrome hand-held game console released by SNK. It was the company\'s first hand-held system and is part of the Neo Geo family. It debuted in Japan in late 1998 but never saw a western release, being exclusive to Japan and smaller Asian markets such as Hong Kong. The Neo Geo Pocket is considered to be an unsuccessful console. Lower than expected sales resulted in its discontinuation in 1999.'),
  (55, 'Pokémon Mini', 'pokemon-mini', 'pokemon_mini.svg', 'http://example.com/', 'The Pokémon Mini is a hand-held game console that was designed and manufactured by Nintendo and themed around the Pokémon media franchise. It is the smallest game system with interchangeable cartridges ever produced by Nintendo, weighing just under two and a half ounces. It was first released in North America on November 16, 2001 then in Japan on December 14, 2001 and in Europe on March 15, 2002. The systems were released in three colors: Wooper Blue, Chikorita Green, and Smoochum Purple. Features of the Pokémon mini include an internal real-time clock, an infrared port used to facilitate multiplayer gaming, a reed switch for detecting shakes, and a motor used to implement force feedback.'),
  (56, 'Watara Supervision', 'watara-supervision', 'watara_supervision.svg', 'http://example.com/', NULL, 'The Watara Supervision, also known as the QuickShot Supervision in the UK, is a monochrome hand-held game console, originating from Asia, and introduced in 1992 as a cut-price competitor for Nintendo\'s Game Boy. One unique feature of the Supervision was that it could be linked up to a television via a link cable. Games played in this way would display in four colors, much like Nintendo\'s Super Game Boy add-on for the SNES. A full color TV link was also in the works, but because of the Supervision\'s failure to make a major impression among gamers it was canceled, along with the games which were in development for it. Though the machine garnered some attention at launch (mainly due to the low price for the machine and its games, which many felt might enable it to make inroads into Nintendo\'s market share) it was ultimately unsuccessful in unseating the Game Boy from its position as the world\'s most popular hand-held. Reasons commonly cited are the poor quality screen which was prone to blurring and made following the action difficult, a general lack of games and the simplistic nature of those that were released.'),
  (57, 'VTech CreatiVision', 'vtech-creativision', 'vtech_creativision.svg', 'http://example.com/', NULL, 'The Video Technology CreatiVision is a hybrid computer and home video game console introduced by VTech in 1981 and released in 1982. The hybrid unit was similar in concept to computers such as the APF Imagination Machine, the older VideoBrain Family Computer, and to a lesser extent the Intellivision game console and Coleco Adam computer, all of which anticipated the trend of video game consoles becoming more like low-end computers. The CreatiVision console sported an 8-bit Rockwell 6502 CPU at a speed of 2 MHz, 1KB of RAM and 16KB of Video RAM, and had a graphics resolution of 256 × 192 with 16 colors and 32 sprites. The console had two integrated joystick/membrane keypad controllers (much like the ColecoVision and Atari 5200) which, when set in a special compartment on top of the console, could be used as a computer keyboard. The CreatiVision had interfaces for a cassette player, an extra rubber keyboard, floppy disk drive, parallel I/O interface, modem, Centronics printer and one memory expansion module for use with the Basic language cartridge.'),
  (58, 'Game.com', 'game-com', 'game_com.svg', 'http://example.com/', 'The Game.com is a fifth-generation handheld game console released by Tiger Electronics in August 1997. A smaller version, the Game.com Pocket Pro, was released in mid-1999. The first version of the Game.com can be connected to a 14.4 kbit/s modem for Internet connectivity; hence its name referencing the top level domain .com. It was the first video game console to include a touchscreen and the first hand-held console to include Internet connectivity. The Game.com sold less than 300,000 units and was discontinued in 2000 because of poor sales. '),
  (59, 'Game Master', 'game-master', 'game_master.svg', 'http://example.com/', 'The Game Master is a handheld game console manufactured by Hartung, and designed to compete with the Nintendo Game Boy. In Germany it was marketed by Hartung itself, while in the UK it was released as the Systema 2000. It was also sold under alternate names in other countries, including Super Game and Game Tronic. The Game Master has a 64 x 64 monochrome LCD screen capable of displaying graphics on par with the Atari 2600.'),
  (60, 'Super Cassette Vision', 'super-cassette-vision', 'super_cassette_vision.svg', 'http://example.com/', 'The Super Cassette Vision is a home video game console made by Epoch Co. and released in Japan on July 17, 1984 and in Europe, specifically France, later in 1984. It competed with the Nintendo Famicom and Sega SG-1000 in Japan. The system did not take off, and was unable to match the massive popularity of the Nintendo Famicom, leading Epoch to drop out of the console market by 1987. '),
  (61, 'ZX Spectrum +3', 'zx-spectrum-plus3', 'zx_spectrum_plus3.svg', 'http://example.com/', 'The ZX Spectrum is an 8-bit personal home computer released in the United Kingdom in 1982 by Sinclair Research. Referred to during development as the ZX81 Colour and ZX82, it was launched as the ZX Spectrum by Sinclair to highlight the machine\'s colour display, compared with the black and white of its predecessor, the ZX81. The Spectrum was released as eight different models, ranging from the entry level with 16 KB RAM released in 1982 to the ZX Spectrum +3 with 128 KB RAM and built in floppy disk drive in 1987; together they sold over 5 million units worldwide. The Spectrum was among the first mainstream-audience home computers in the UK, similar in significance to the Commodore 64 in the US. The introduction of the ZX Spectrum led to a boom in companies producing software and hardware for the machine. Some credit it as the machine which launched the UK IT industry. Licensing deals and clones followed, and earned Clive Sinclair a knighthood for "services to British industry". The Commodore 64, Dragon 32, Oric-1, Oric Atmos, BBC Micro and later the Amstrad CPC range were rivals to the Spectrum in the UK market during the early 1980s. While the machine was officially discontinued in 1992, new software titles continue to be released.'),
  (62, 'Commodore 64\r\n (Tapes)', 'commodore-64-tapes', 'commodore_64_2.svg', 'http://example.com/', NULL, 'The Commodore 64, also known as the C64 or the CBM 64, is an 8-bit home computer introduced in January 1982 by Commodore International. It has been listed in the Guinness World Records as the highest-selling single computer model of all time, with independent estimates placing the number sold between 10 and 17 million units. With support for multicolor sprites and a custom chip for waveform generation, the C64 could create superior visuals and audio compared to systems without such custom hardware. '),
  (63, 'Commodore 64\r\n (Preservation Project)', 'commodore-64-pp', 'commodore_64_2.svg', 'http://example.com/', NULL, 'The Commodore 64, also known as the C64 or the CBM 64, is an 8-bit home computer introduced in January 1982 by Commodore International. It has been listed in the Guinness World Records as the highest-selling single computer model of all time, with independent estimates placing the number sold between 10 and 17 million units. With support for multicolor sprites and a custom chip for waveform generation, the C64 could create superior visuals and audio compared to systems without such custom hardware. '),
  (64, 'Commodore VIC-20', 'commodore-vic-20', 'commodore_vic_20.svg', 'http://example.com/', NULL, 'The VIC-20 is an 8-bit home computer that was sold by Commodore Business Machines. The VIC-20 was announced in 1980, roughly three years after Commodore\'s first personal computer, the PET. The VIC-20 was the first computer of any description to sell one million units.'),
  (65, 'Commodore Plus/4', 'commodore-plus-4', 'commodore_plus_4.svg', 'http://example.com/', NULL, 'The Commodore Plus/4 was a home computer released in 1984. The "Plus/4" name refers to the four-application ROM resident office suite (word processor, spreadsheet, database, and graphing). It was billed as "the productivity computer with software built-in". It had some success in Eastern Europe, but was less popular in Western Europe. A total flop in the United States, it was derided as the "Minus/60"—a pun on the difference between the Plus/4 and the dominant  Commodore 64.'),
  (66, '3DO', '3do', '3do.svg', NULL, 'http://example.com/', 'The 3DO Interactive Multiplayer is a home video game console platform developed by The 3DO Company. Conceived by entrepreneur and Electronic Arts founder Trip Hawkins, the 3DO was not a console manufactured by the company itself, but a series of specifications, originally designed by Dave Needle and R. J. Mical of New Technologies Group, that could be licensed by third parties. Panasonic produced the first models in 1993, and further renditions of the hardware were released in 1994 by GoldStar (now LG Corp) and in 1995 by Sanyo. Despite a highly promoted launch (including being named Time magazine\'s "1993 Product of the Year") and a host of cutting-edge technologies, the 3DO\'s high price and an over-saturated console market prevented the system from achieving success comparable to veteran competitors Sega and Nintendo. As a result, it was discontinued in late 1996.'),
  (67, 'Amiga CD', 'amiga-cd', 'amiga_cd.svg', NULL, NULL, NULL),
  (68, 'FM Towns', 'fm-towns', 'fm_towns.svg', NULL, 'http://example.com/', 'FM Towns system is a Japanese PC variant, built by Fujitsu from February 1989 to the summer of 1997. It started as a proprietary PC variant intended for multimedia applications and PC games, but later became more compatible with regular PCs. The "FM" part of the name means "Fujitsu Micro" like their earlier products, while the "Towns" part is derived from the code name the system was assigned while in development, "Townes". This refers to Charles Townes, one of the winners of the 1964 Nobel Prize in Physics, following a custom of Fujitsu at the time to code name PC products after Nobel Prize winners. The e in "Townes" was dropped when the system went into production to make it clearer that the term was to be pronounced like the word "towns" rather than the potential "tow-nes".'),
  (69, 'Philips CD-i', 'cd-i', 'cd_i.svg', NULL, 'http://example.com/', 'The Philips CD-i is an interactive multimedia CD player developed and marketed by Dutch company Philips, who supported it from December 1991 to late 1998. It was created to provide more functionality than an audio CD player or game console, but at a lower price than a personal computer with a CD-ROM drive. The cost savings were due to the lack of a floppy drive, keyboard, mouse, monitor and less operating system software. "CD-i" also refers to the multimedia Compact Disc standard used by the CD-i console, also known as Green Book, which was co-developed by Philips and Sony. In addition to games, educational and multimedia reference titles were produced, such as interactive encyclopedias and museum tours, which were popular before public Internet access was widespread. The CD-i was also one of the earliest game systems to implement Internet features, including subscriptions, web browsing, downloading, e-mail, and online play. This was facilitated by the use of an additional hardware modem and "CD-Online" disc (renamed Web-i in the US[), which Philips initially released in Britain in 1995.'),
  (70, 'Amiga CD³²', 'amiga-cd32', 'amiga_cd32.svg', NULL, 'http://example.com/', 'The Amiga CD32, styled Amiga CD32 and code-named "Spellbound", is a home video game console developed by Commodore and released in western Europe, Australia, Canada and Brazil. It was first announced at the Science Museum in London on July 16, 1993, and was released in September of the same year. The CD32 is part of a family of Amiga computers and other hardware. It uses CD-ROM as its storage medium. It was based on Commodore\'s Advanced Graphics Architecture chipset, and is of similar specification to the Amiga 1200 computer. Using third party devices, it is possible to upgrade the CD32 with keyboard, floppy drive, hard drive, RAM and mouse, turning it into the equivalent of an Amiga 1200 personal computer.'),
  (71, 'Neo Geo CD', 'neo-geo-cd', 'neo_geo_cd.svg', NULL, NULL, NULL),
  (72, 'Picno', 'picno', 'picno.svg', 'http://example.com/', NULL, 'The Konami Picno is a drawing tablet that uses a TV screen for its display. A second model was produced one year later. Not much is known about this machine, apart from the fact that Love Plus producer Akari Uchida worked on it.'),
  (73, 'V.Smile', 'v-smile', 'v_smile.svg', 'http://example.com/', NULL, 'The V.Smile is a 128-bit educational game system by VTech. It is designed for children ages 3 to 6, but offers software designed for several age groups between 3-9. Titles are available on ROM cartridges called "Smartridges", to play off the system\'s educational nature. The graphics are primarily sprite-based. The console is often sold bundled with a particular game. With most of them having a game called "Alphabet Park Adventure." Several variants of the V.Smile console are sold including handheld versions, or models with added functionality such as touch tablet integrated controllers or microphones.');


CREATE TABLE IF NOT EXISTS `consoles_emulators` (
  `console_id` int(10) unsigned NOT NULL,
  `emulator_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`console_id`,`emulator_id`),
  UNIQUE KEY `console_id_emulator_id` (`console_id`,`emulator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `consoles_emulators` (`console_id`, `emulator_id`) VALUES
  (1, 5),
  (1, 6),
  (2, 7),
  (2, 8),
  (3, 22),
  (4, 9),
  (4, 10),
  (5, 11),
  (5, 16),
  (6, 1),
  (6, 3),
  (7, 1),
  (7, 12),
  (8, 6),
  (8, 13),
  (8, 57),
  (9, 13),
  (9, 24),
  (10, 13),
  (10, 24),
  (11, 48),
  (11, 57),
  (12, 30),
  (12, 44),
  (13, 17),
  (14, 6),
  (14, 21),
  (15, 14),
  (15, 15),
  (15, 19),
  (18, 4),
  (19, 1),
  (19, 28),
  (19, 29),
  (20, 42),
  (21, 1),
  (21, 6),
  (22, 31),
  (22, 32),
  (23, 6),
  (23, 13),
  (23, 30),
  (24, 6),
  (24, 13),
  (24, 30),
  (25, 1),
  (26, 39),
  (26, 40),
  (27, 37),
  (27, 38),
  (29, 43),
  (30, 13),
  (30, 15),
  (30, 23),
  (31, 13),
  (31, 48),
  (31, 57),
  (32, 47),
  (32, 48),
  (32, 57),
  (33, 47),
  (33, 48),
  (34, 1),
  (34, 48),
  (35, 13),
  (35, 43),
  (35, 44),
  (36, 44),
  (36, 59),
  (37, 1),
  (38, 1),
  (38, 34),
  (38, 35),
  (38, 36),
  (39, 1),
  (39, 2),
  (40, 1),
  (41, 1),
  (42, 1),
  (43, 56),
  (44, 60),
  (45, 1),
  (45, 36),
  (45, 49),
  (45, 50),
  (46, 1),
  (46, 51),
  (46, 52),
  (46, 53),
  (47, 33),
  (48, 33),
  (49, 1),
  (49, 6),
  (50, 1),
  (50, 6),
  (51, 49),
  (53, 1),
  (53, 6),
  (54, 1),
  (54, 6),
  (55, 46),
  (56, 54),
  (57, 1),
  (58, 1),
  (59, 1),
  (60, 1),
  (61, 1),
  (61, 61),
  (62, 1),
  (62, 12),
  (63, 1),
  (63, 12),
  (64, 12),
  (65, 12),
  (66, 45),
  (68, 1),
  (69, 1),
  (70, 39),
  (70, 40);

CREATE TABLE IF NOT EXISTS `directory_info` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `console` varchar(100) NOT NULL,
  `region` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Extra directory info so the upload scripts know where to locate the ROM.';
INSERT INTO `directory_info` (`id`, `console`, `region`) VALUES
  (1, 'Sony - PlayStation 2', 'NTSC-U'),
  (2, 'Sony - PlayStation', 'NTSC-J'),
  (3, 'Sony - PlayStation', 'NTSC-U'),
  (4, 'Sony - PlayStation', 'PAL'),
  (5, 'Sony - PlayStation Portable', NULL),
  (6, 'Sega - Saturn', NULL),
  (7, 'Sega - Dreamcast', NULL),
  (8, 'Nintendo - GameCube', 'NTSC-J'),
  (9, 'Nintendo - GameCube', 'NTSC-U'),
  (10, 'Nintendo - GameCube', 'PAL'),
  (11, 'Nintendo - Nintendo 64 BigEndian', NULL),
  (12, 'Nintendo - Nintendo DS (Decrypted)', NULL),
  (13, 'Nintendo - Nintendo DS (Download Play)', NULL),
  (14, 'Nintendo - Nintendo DSi (DLC)', NULL),
  (15, 'Sega - Game Gear', NULL),
  (16, 'Atari - 2600', NULL),
  (17, 'Atari - 5200', NULL),
  (18, 'Atari - 7800 [Headered]', NULL),
  (19, 'Atari - Jaguar (64)', NULL),
  (20, 'Atari - Lynx [Headered]', NULL),
  (21, 'Atari - ST', NULL),
  (22, 'Bandai - WonderSwan', NULL),
  (23, 'Bandai - WonderSwan Color', NULL),
  (24, 'Casio - Loopy', NULL),
  (25, 'Commodore - Amiga', NULL),
  (26, 'Nintendo - Virtual Boy', NULL),
  (27, 'Nintendo - Super Nintendo Entertainment System', NULL),
  (28, 'Nokia - N-Gage', NULL),
  (29, 'Nintendo - Nintendo Entertainment System [headered]', NULL),
  (30, 'Nintendo - Game Boy', NULL),
  (31, 'Nintendo - Game Boy Color', NULL),
  (32, 'Nintendo - Game Boy Advance', NULL),
  (33, 'Sega - Mega Drive - Genesis', NULL),
  (34, 'Sega - Master System - Mark III', NULL),
  (35, 'Sega - 32X', NULL),
  (36, 'Sega - PICO', NULL),
  (37, 'Sega - SG-1000', NULL),
  (38, 'Nintendo - Family Computer Disk System [headered]', NULL),
  (39, 'Nintendo - Satellaview', NULL),
  (40, 'Casio - PV-1000', NULL),
  (41, 'Coleco - ColecoVision', NULL),
  (42, 'Emerson - Arcadia 2001', NULL),
  (43, 'Entex - Adventure Vision', NULL),
  (44, 'Fairchild - Channel F', NULL),
  (45, 'Funtech - Super Acan', NULL),
  (46, 'GamePark - GP32', NULL),
  (47, 'GCE - Vectrex', NULL),
  (48, 'Magnavox - Odyssey2', NULL),
  (49, 'Mattel - Intellivision', NULL),
  (50, 'Microsoft - MSX', NULL),
  (51, 'Microsoft - MSX2', NULL),
  (52, 'NEC - PC Engine - TurboGrafx 16', NULL),
  (53, 'NEC - PC Engine SuperGrafx', NULL),
  (54, 'Philips - Videopac+', NULL),
  (55, 'RCA - Studio II', NULL),
  (56, 'SNK - Neo Geo Pocket Color', NULL),
  (57, 'SNK - Neo Geo Pocket', NULL),
  (58, 'Nintendo - Pokemon Mini', NULL),
  (59, 'Watara - Supervision', NULL),
  (60, 'VTech - CreatiVision', NULL),
  (61, 'Tiger - Game.com', NULL),
  (62, 'Hartung - Game Master', NULL),
  (63, 'Epoch - Super Cassette Vision', NULL),
  (64, 'Sinclair - ZX Spectrum +3', NULL),
  (65, 'Commodore - 64', NULL),
  (66, 'Commodore - 64 (Tapes)', NULL),
  (67, 'Commodore - 64 (PP)', NULL),
  (68, 'Commodore - VIC-20', NULL),
  (69, 'Commodore - Plus-4', NULL),
  (70, 'Panasonic - 3DO Interactive Multiplayer', NULL),
  (71, 'Commodore - Amiga CD', NULL),
  (72, 'Fujitsu - FM Towns', NULL),
  (73, 'Philips - Philips CD-i', NULL),
  (74, 'Commodore - Amiga CD32', NULL),
  (75, 'SNK - Neo Geo CD', NULL),
  (76, 'Konami - Picno', NULL),
  (77, 'Tiger - Gizmondo', NULL),
  (78, 'VTech - V.Smile', NULL);

CREATE TABLE IF NOT EXISTS `emulators` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `link` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `emulators` (`id`, `name`, `link`) VALUES
  (1, 'MAME', 'https://www.mamedev.org/index.php'),
  (2, 'WinArcadia', 'http://amigan.1emu.net/releases/'),
  (3, 'Stella', 'https://stella-emu.github.io/'),
  (4, 'Atari800', 'https://atari800.github.io/'),
  (5, 'ePSXe', 'https://www.epsxe.com/'),
  (6, 'Mednafen', 'https://mednafen.github.io/'),
  (7, 'PCSX2', 'https://pcsx2.net/'),
  (8, 'Play!', 'http://purei.org/'),
  (9, 'Project64', 'https://www.pj64-emu.com/'),
  (10, 'Mupen64Plus', 'https://mupen64plus.org/'),
  (11, 'Redream', 'https://redream.io/'),
  (12, 'VICE', 'http://vice-emu.sourceforge.net/'),
  (13, 'higan', 'https://byuu.org/emulation/higan/'),
  (14, 'DeSmuME ', 'http://desmume.org/'),
  (15, 'no$gba', 'http://problemkaputt.de/gba.htm'),
  (16, 'Reicast', 'http://reicast.com/'),
  (17, 'PPSSPP', 'https://www.ppsspp.org/'),
  (19, 'melonDS', 'http://melonds.kuribo64.net/'),
  (20, 'SSF', 'http://www.geocities.jp/mj3kj8o5/ssf/index.html'),
  (21, 'uoYabause', 'http://www.uoyabause.org/'),
  (22, 'Dolphin', 'https://dolphin-emu.org/'),
  (23, 'mGBA', 'https://mgba.io/'),
  (24, 'VBA-M', 'https://vba-m.com/'),
  (25, 'EightyOne', 'https://sourceforge.net/projects/eightyone-sinclair-emulator/'),
  (26, 'Fuse', 'http://fuse-emulator.sourceforge.net/'),
  (27, 'Speccy', 'http://fms.komkon.org/Speccy/'),
  (28, 'A7800', 'http://7800.8bitdev.org/index.php/A7800_Emulator'),
  (29, 'ProSystem', 'http://gstanton.github.io/ProSystem1_3/'),
  (30, 'BizHawk', 'http://tasvideos.org/BizHawk/ReleaseHistory.html'),
  (31, 'Steem SSE', 'https://sourceforge.net/projects/steemsse/'),
  (32, 'Hatari', 'http://hatari.tuxfamily.org/'),
  (33, 'openMSX', 'http://openmsx.org/'),
  (34, 'ColEm', 'http://fms.komkon.org/ColEm/'),
  (35, 'CoolCV', 'http://www.colecovision.ca/coolcv.php'),
  (36, 'Pantheon', 'http://bostjan-grandovec.si'),
  (37, 'VBjin', 'https://emu.zone/resources/vbjin-svn-103.144/'),
  (38, 'VBjin-OVR', 'https://github.com/braindx/vbjin-ovr'),
  (39, 'WinUAE', 'http://www.winuae.net/'),
  (40, 'FS-UAE', 'https://fs-uae.net'),
  (41, 'vdmgr ', 'http://www.geocities.jp/g_lsluk/download.html'),
  (42, 'Virtual Jaguar', 'http://icculus.org/virtualjaguar/'),
  (43, 'Mesen', 'https://www.mesen.ca/'),
  (44, 'Snes9x', 'http://www.snes9x.com/'),
  (45, '4DO', 'https://sourceforge.net/projects/fourdo/'),
  (46, 'PokeMini', 'https://sourceforge.net/projects/pokemini/'),
  (47, 'PicoDrive (RetroArch)', 'https://notaz.gp2x.de/pico.php'),
  (48, 'Kega Fusion', 'https://www.carpeludum.com/kega-fusion/'),
  (49, 'O2EM', 'http://o2em.sourceforge.net/'),
  (50, 'O2EM2', 'http://o2em2.sourceforge.net/'),
  (51, 'FreeIntv', 'https://sourceforge.net/projects/freeintv/'),
  (52, 'jzIntv', 'http://www.spatula-city.org/~im14u2c/intv/'),
  (53, 'Nostalgia', 'http://www.intellivision.us/intvgames/nostalgia/nostalgia.php'),
  (54, 'Wataroo', 'http://tailchao.com/Wataroo/index.php'),
  (55, 'Potator', 'https://sourceforge.net/projects/potator/'),
  (56, 'GeePee32', 'http://users.skynet.be/firefly/gp32/'),
  (57, 'Genesis Plus GX (RetroArch)', 'https://bitbucket.org/eke/genesis-plus-gx'),
  (58, 'creatiVision emulator', 'https://sourceforge.net/projects/creativisionemulator/'),
  (59, 'no$sns', 'http://problemkaputt.de/sns.htm'),
  (60, 'ParaJVE', 'http://www.vectrex.fr/ParaJVE/'),
  (61, 'Spectaculator', 'redacted');

CREATE TABLE IF NOT EXISTS `error_log` (
  `name` varchar(255) DEFAULT NULL,
  `console` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `files` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rom_id` int(10) unsigned NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL DEFAULT '0',
  `size` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `rom_id` (`rom_id`),
  KEY `size` (`size`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hosters` (
  `id` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `order` int(2) unsigned NOT NULL,
  `icon_html` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `order` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `hosters` (`id`, `name`, `order`, `icon_html`) VALUES
  ('1fichier', '1fichier', 13, '<img src="/static/img/hoster_logos/1fichier.svg" class="fac-hoster">'),
  ('filecloud', 'filecloud.io', 7, '<i class="fas fa-fw fa-cloud"></i>'),
  ('filescdn', 'Filescdn', 8, '<img src="/static/img/hoster_logos/filescdn.svg" class="fac-hoster">'),
  ('gdrive', 'Google Drive', 2, '<i class="fab fa-fw fa-google-drive"></i>'),
  ('gdrive_folder', 'Google Drive (Folder)', 1, '<i class="fac-hoster fa-drive-folder"><i class="fas fa-folder"></i><i class="fab fa-google-drive fa-inverse"></i></i>'),
  ('gdrive_single', 'Google Drive (ISO Link)', 3, '<i class="fab fa-fw fa-google-drive"></i>'),
  ('letsupload', 'LetsUpload', 3, '<img src="/static/img/hoster_logos/letsupload.svg" class="fac-hoster">'),
  ('megaup', 'MegaUp', 3, '<img src="/static/img/hoster_logos/megaup.svg" class="fac-hoster">'),
  ('openload', 'Openload', 6, '<img src="/static/img/hoster_logos/openload.svg" class="fac-hoster">'),
  ('shareonline_biz', 'Share-Online', 12, '<img src="/static/img/hoster_logos/shareonline.svg" class="fac-hoster">'),
  ('uploaded', 'Uploaded.net', 11, '<img src="/static/img/hoster_logos/uploaded.svg" class="fac-hoster">'),
  ('uploadhaven', 'UploadHaven', 4, '<img src="/static/img/hoster_logos/uploadhaven.svg" class="fac-hoster">'),
  ('uploadhaven_single', 'UploadHaven (ISO Link)', 5, '<img src="/static/img/hoster_logos/uploadhaven.svg" class="fac-hoster">'),
  ('uptobox', 'UptoBox', 10, '<img src="/static/img/hoster_logos/uptobox.svg" class="fac-hoster">'),
  ('userscloud', 'Userscloud', 4, '<i class="fa-stack fa-fw"><i class="fas fa-square fa-stack-2x"></i><i class="fas fa-star fa-stack-1x fa-inverse"></i></i>'),
  ('zippyshare', 'Zippyshare', 9, '<img src="/static/img/hoster_logos/zippyshare.svg" class="fac-hoster">');

CREATE TABLE IF NOT EXISTS `languages` (
  `id` varchar(3) NOT NULL,
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `languages` (`id`, `name`) VALUES
  ('aa', 'Afar'),
  ('ab', 'Abkhazian'),
  ('ae', 'Avestan'),
  ('af', 'Afrikaans'),
  ('ak', 'Akan'),
  ('am', 'Amharic'),
  ('an', 'Aragonese'),
  ('ar', 'Arabic'),
  ('as', 'Assamese'),
  ('av', 'Avaric'),
  ('ay', 'Aymara'),
  ('az', 'Azerbaijani'),
  ('ba', 'Bashkir'),
  ('be', 'Belarusian'),
  ('bg', 'Bulgarian'),
  ('bh', 'Bihari languages'),
  ('bi', 'Bislama'),
  ('bm', 'Bambara'),
  ('bn', 'Bengali'),
  ('bo', 'Tibetan'),
  ('br', 'Breton'),
  ('bs', 'Bosnian'),
  ('ca', 'Catalan'),
  ('ce', 'Chechen'),
  ('ch', 'Chamorro'),
  ('co', 'Corsican'),
  ('cr', 'Cree'),
  ('cs', 'Czech'),
  ('cu', 'Church Slavic'),
  ('cv', 'Chuvash'),
  ('cy', 'Welsh'),
  ('da', 'Danish'),
  ('de', 'German'),
  ('dv', 'Divehi'),
  ('dz', 'Dzongkha'),
  ('ee', 'Ewe'),
  ('el', 'Greek'),
  ('en', 'English'),
  ('eo', 'Esperanto'),
  ('es', 'Spanish'),
  ('et', 'Estonian'),
  ('eu', 'Basque'),
  ('fa', 'Persian'),
  ('fi', 'Finnish'),
  ('fj', 'Fiji'),
  ('fo', 'Faeroese'),
  ('fr', 'French'),
  ('fy', 'Frisian'),
  ('ga', 'Irish'),
  ('gd', 'Scots Gaelic'),
  ('gl', 'Galician'),
  ('gn', 'Guarani'),
  ('gu', 'Gujarati'),
  ('ha', 'Hausa'),
  ('he', 'Hebrew'),
  ('hi', 'Hindi'),
  ('hr', 'Croatian'),
  ('hu', 'Hungarian'),
  ('hy', 'Armenian'),
  ('ia', 'Interlingua'),
  ('id', 'Indonesian'),
  ('ie', 'Interlingue'),
  ('ik', 'Inupiak'),
  ('in', 'former Indonesian'),
  ('is', 'Icelandic'),
  ('it', 'Italian'),
  ('iu', 'Inuktitut (Eskimo)'),
  ('iw', 'former Hebrew'),
  ('ja', 'Japanese'),
  ('ji', 'former Yiddish'),
  ('jw', 'Javanese'),
  ('ka', 'Georgian'),
  ('kk', 'Kazakh'),
  ('kl', 'Greenlandic'),
  ('km', 'Cambodian'),
  ('kn', 'Kannada'),
  ('ko', 'Korean'),
  ('ks', 'Kashmiri'),
  ('ku', 'Kurdish'),
  ('ky', 'Kirghiz'),
  ('la', 'Latin'),
  ('ln', 'Lingala'),
  ('lo', 'Laothian'),
  ('lt', 'Lithuanian'),
  ('lv', 'Latvian, Lettish'),
  ('mg', 'Malagasy'),
  ('mi', 'Maori'),
  ('mk', 'Macedonian'),
  ('ml', 'Malayalam'),
  ('mn', 'Mongolian'),
  ('mo', 'Moldavian'),
  ('mr', 'Marathi'),
  ('ms', 'Malay'),
  ('mt', 'Maltese'),
  ('my', 'Burmese'),
  ('na', 'Nauru'),
  ('ne', 'Nepali'),
  ('nl', 'Dutch'),
  ('no', 'Norwegian'),
  ('oc', 'Occitan'),
  ('om', '(Afan) Oromo'),
  ('or', 'Oriya'),
  ('pa', 'Punjabi'),
  ('pl', 'Polish'),
  ('ps', 'Pashto, Pushto'),
  ('pt', 'Portuguese'),
  ('qu', 'Quechua'),
  ('rm', 'Rhaeto-Romance'),
  ('rn', 'Kirundi'),
  ('ro', 'Romanian'),
  ('ru', 'Russian'),
  ('rw', 'Kinyarwanda'),
  ('sa', 'Sanskrit'),
  ('sd', 'Sindhi'),
  ('sg', 'Sangro'),
  ('sh', 'Serbo-Croatian'),
  ('si', 'Singhalese'),
  ('sk', 'Slovak'),
  ('sl', 'Slovenian'),
  ('sm', 'Samoan'),
  ('sn', 'Shona'),
  ('so', 'Somali'),
  ('sq', 'Albanian'),
  ('sr', 'Serbian'),
  ('ss', 'Siswati'),
  ('st', 'Sesotho'),
  ('su', 'Sundanese'),
  ('sv', 'Swedish'),
  ('sw', 'Swahili'),
  ('ta', 'Tamil'),
  ('te', 'Telugu'),
  ('tg', 'Tajik'),
  ('th', 'Thai'),
  ('ti', 'Tigrinya'),
  ('tk', 'Turkmen'),
  ('tl', 'Tagalog'),
  ('tn', 'Tswana'),
  ('to', 'Tonga (Tonga Islands)'),
  ('tr', 'Turkish'),
  ('ts', 'Tsonga'),
  ('tt', 'Tatar'),
  ('tw', 'Twi'),
  ('ty', 'Tahitian'),
  ('ug', 'Uighur'),
  ('uk', 'Ukrainian'),
  ('ur', 'Urdu'),
  ('uz', 'Uzbek'),
  ('ve', 'Venda'),
  ('vi', 'Vietnamese'),
  ('vo', 'Volapük'),
  ('wa', 'Walloon'),
  ('wo', 'Wolof'),
  ('xh', 'Xhosa'),
  ('yi', 'Yiddish'),
  ('yo', 'Yoruba'),
  ('za', 'Zhuang'),
  ('zh', 'Chinese'),
  ('zu', 'Zulu');

CREATE TABLE IF NOT EXISTS `links` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `rom_id` int(11) unsigned NOT NULL,
  `file_name` varchar(2000) DEFAULT NULL,
  `link` varchar(2083) DEFAULT NULL,
  `link_safe` varchar(2083) DEFAULT NULL,
  `status` enum('UPLOADING','DONE') NOT NULL DEFAULT 'UPLOADING',
  `host` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `rom_id` (`rom_id`),
  KEY `file_name` (`file_name`(1024)),
  KEY `status` (`status`),
  KEY `host` (`host`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `regions` (
  `name` varchar(100) NOT NULL,
  `iso_3166_1_alpha_2` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `regions` (`name`, `iso_3166_1_alpha_2`) VALUES
  ('Argentina', 'ar'),
  ('Asia', 'asi'),
  ('Asia, Europe', 'asi,eu'),
  ('Asia, Korea', 'asi,kr'),
  ('Australia', 'au'),
  ('Austria', 'at'),
  ('Brasil', 'br'),
  ('Brazil', 'br'),
  ('Brazil, Korea', 'br,kr'),
  ('Brazil, Portugal', 'br,pt'),
  ('Canada', 'ca'),
  ('China', 'cn'),
  ('Croatia', 'hr'),
  ('Crotia', 'hr'),
  ('Czech', 'cz'),
  ('Denmark', 'dk'),
  ('Europe', 'eu'),
  ('Europe, Asia', 'eu,asi'),
  ('Europe, Australia', 'eu,au'),
  ('Europe, Brazil', 'eu,br'),
  ('Europe, Canada', 'eu,ca'),
  ('Europe, Korea', 'eu,kr'),
  ('Finland', 'fi'),
  ('France', 'fr'),
  ('France, Spain', 'fr,es'),
  ('Germany', 'de'),
  ('Greece', 'gr'),
  ('Hong Kong', 'hk'),
  ('Hungary', 'hu'),
  ('India', 'in'),
  ('Ireland', 'ie'),
  ('Italy', 'it'),
  ('Japan', 'jp'),
  ('Japan, Asia', 'sp,asi'),
  ('Japan, Brazil', 'jp,br'),
  ('Japan, Europe', 'jp,eu'),
  ('Japan, Europe, Brazi', 'jp,eu,br'),
  ('Japan, Europe, Brazil', 'jp,eu,br'),
  ('Japan, Hong Kong', 'jp,hk'),
  ('Japan, Korea', 'jp,kr'),
  ('Japan, Korea, Asia', 'jp,kr,asi'),
  ('Japan, USA', 'jp,us'),
  ('Japan, USA, Brazil', 'jp,us,br'),
  ('Japan, USA, Korea', 'jp,us,kr'),
  ('Korea', 'kr'),
  ('Latin America', 'unk'),
  ('Netherlands', 'nl'),
  ('Norway', 'no'),
  ('Poland', 'pl'),
  ('Portugal', 'pt'),
  ('Russia', 'ru'),
  ('Scandinavia', 'unk'),
  ('Spain', 'es'),
  ('Sweden', 'se'),
  ('Taiwan', 'tw'),
  ('UK', 'gb'),
  ('Unknown', 'unk'),
  ('USA', 'us'),
  ('USA, Asia', 'us,asi'),
  ('USA, Asia, Korea', 'us,asi,kr'),
  ('USA, Australia', 'us,au'),
  ('USA, Brazil', 'us,br'),
  ('USA, Europe', 'us,eu'),
  ('USA, Europe, Brazil', 'us,eu,br'),
  ('USA, Europe, Korea', 'us,eu,kr'),
  ('USA, Japan', 'us,jp'),
  ('USA, Korea', 'us,kr'),
  ('World', 'wor');

CREATE TABLE IF NOT EXISTS `roms` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dir_info_id` int(10) unsigned NOT NULL,
  `uploading` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `last_upload` int(11) unsigned NOT NULL,
  `slug` varchar(255) NOT NULL,
  `console` varchar(255) NOT NULL,
  `name_original` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `region` varchar(50) DEFAULT NULL,
  `disc` int(2) unsigned DEFAULT NULL,
  `languages` varchar(255) DEFAULT NULL,
  `version` varchar(255) DEFAULT NULL,
  `devstatus` varchar(255) DEFAULT NULL,
  `additional` varchar(255) DEFAULT NULL,
  `special` varchar(255) DEFAULT NULL,
  `license` varchar(255) DEFAULT NULL,
  `status` int(10) unsigned DEFAULT NULL,
  `nointro_id` varchar(50) DEFAULT NULL,
  `nointro_system_id` varchar(50) DEFAULT NULL,
  `redump_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_per_system` (`slug`,`console`,`name_original`),
  KEY `nointro_system_id` (`nointro_system_id`),
  KEY `redump_id` (`redump_id`),
  KEY `nointro-id` (`nointro_id`),
  KEY `name_original` (`name_original`),
  KEY `name` (`name`),
  KEY `console` (`console`),
  KEY `region` (`region`),
  KEY `slug` (`slug`),
  KEY `dir_info` (`dir_info_id`),
  KEY `last_upload` (`last_upload`),
  KEY `uploading` (`uploading`),
  FULLTEXT KEY `fulltext` (`additional`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `site` (
  `name` varchar(50) NOT NULL,
  `value` text DEFAULT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `votes` (
  `uid` varbinary(16) NOT NULL,
  `rom_id` int(11) unsigned NOT NULL,
  PRIMARY KEY (`uid`,`rom_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;